version: '3.5'

services:
 core:
   env_file: .env
   environment:
     - 'CLIENT_DB_CONNECTIONSTRING=jdbc:snowflake://alligator.eu-central-1.snowflakecomputing.com/?db=DEV_GLUNDE&warehouse=WH_DEV&CLIENT_SESSION_KEEP_ALIVE=true&CLIENT_SESSION_KEEP_ALIVE_HEARTBEAT_FREQUENCY=900&CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX=false&CLIENT_METADATA_USE_SESSION_DATABASE=true'
     - SNOWFLAKE_DATABASE=DEV_GLUNDE
     - CLIENT_DB_TYPE=snowflake_client_db
     - ENABLE_BETA_FEATURES=false
     - 'USE_UNSECURE_DEFAULT_ENCRYPTION_KEYS=false'
     - 'PLJAVA_VMOPTIONS=-Djava.security.egd=file:///dev/urandom -Xms128M -Xss2M'
     - DOWNLOAD_DEMO_DATA=true
     - 'GUI_USER_NAME=dvb'
     - 'GUI_USER_PASSWORD=start123'
     - 'GUI_USER_GROUP=dvb_admin'
     - 'GUI_USER_EMAIL=your@mail.com'
   image: 'datavaultbuilder/core:${DVB_TAG}'
   volumes:
     - files:/files
   secrets:
     - systems_password_public_key
     - systems_password_private_key
     - systems_password_private_key_password
     - core_dbadmin_password
     - authenticator_password
     - scheduler_password
     - datavault_builder_license
   networks:
     dvbnet2:
   restart: always

 connection_pool:
   env_file: .env
   environment:
     - CORE_POOL_MAX_CONNECTIONS=50
     - CLIENTDB_POOL_MAX_CONNECTIONS=50
     - CLIENTDB_POOL_CONNECTION_TIMEOUT_MS=3600000
     #- 'JAVA_OPTS=-Dnet.snowflake.jdbc.loggerImpl=net.snowflake.client.log.SLF4JLogger'
     - METRICS_PROVIDER=micrometer-prometheus
   image: 'datavaultbuilder/connection_pool:${DVB_TAG}'
   volumes:
     - files:/files
     - pddb:/opt/datavaultbuilder/var/lib/pddb
   secrets:
     - systems_password_public_key
     - systems_password_private_key
     - systems_password_private_key_password
     - core_dbadmin_password
     - authenticator_password
   networks:
     dvbnet2:
       aliases:
         - connectionpool
   restart: always       

 webgui:
   env_file: .env
   environment:
     - 'DAV_USER=dvb'
     - 'DAV_PASSWORD=start123'
     - DISABLE_IPV6=false
   image: 'datavaultbuilder/webgui:rel_5.3.0.1_initial_install_only'
   ports:
     - '9998:80'
       #     - '443:443'
       #   secrets:
           #     - ssl_fullchain
           #     - ssl_private_key
   volumes:
     - files:/files    
   networks:
     dvbnet2:
   restart: always

 scheduler:
   env_file: .env
   environment:
     - MAX_SERVICE_CONNECTION_AGE=3600
     - 'PGAGENT_OPTIONS=-l 2'
   image: 'datavaultbuilder/scheduler:${DVB_TAG}'
   secrets:
     - scheduler_password    
   networks:
     dvbnet2:
   restart: always

 api:
   env_file: .env
   environment:
     - CONNECTION_POOL=30
   image: 'datavaultbuilder/api:${DVB_TAG}'
   ports:
     - '12334:12334'
   secrets:
     - authenticator_password
     - core_dbadmin_password    
   networks:
     dvbnet2:
   restart: always
  
 prometheus:
  image: datavaultbuilder/prometheus:${DVB_TAG}
  volumes:
    - prometheus:/var/lib/prometheus
  networks:
    - dvbnet2
  restart: always

 grafana:
    environment:
      - 'GF_SERVER_ROOT_URL=http://104.47.154.248:9998/grafana'
      #- 'GF_SECURITY_ADMIN_PASSWORD=someSecretPassword!'
      - GF_AUTH_ANONYMOUS_ENABLED=true
    image: datavaultbuilder/grafana:${DVB_TAG}
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - dvbnet2
    restart: always

secrets:
   systems_password_public_key:
     file: secrets/systems_password_public_key.txt
   systems_password_private_key:
     file: secrets/systems_password_private_key.txt
   systems_password_private_key_password:
     file: secrets/systems_password_private_key_password.txt
   core_dbadmin_password:
     file: secrets/core_dbadmin_password.txt
   authenticator_password:
     file: secrets/authenticator_password.txt
   scheduler_password:
     file: secrets/scheduler_password.txt
   datavault_builder_license:
     file: datavault_builder_license.lic
   ssl_fullchain:
     file: secrets/ssl-fullchain.pem
   ssl_private_key:
     file: secrets/domain-com-key.pem  
   scheduler_password:
     file: secrets/scheduler_password.txt     
   authenticator_password:
     file: secrets/authenticator_password.txt
   core_dbadmin_password:
     file: secrets/core_dbadmin_password.txt     

volumes:
   files:
   pddb:
   exa:
   prometheus:
   grafana:

networks:
   dvbnet2:
      driver: bridge
      ipam:
         driver: default

